[programs.localnet]
myepicproject = "CJSaikztCUF1bMPhrLP1Q4GtGMNgEZ4ELb5qeVBBcB7s"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/vitor/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
